In [4]:
import numpy as np
np.random.seed(47)

In [ ]:
# Ejercicio 1: Array de 10 elementos con cero
arr1 = np.zeros(10)
print(arr1)

In [ ]:
# Ejercicio 2: Array con numeros del 1 al 20
arr2 = np.arange(1, 21)
print(arr2)

In [ ]:
# Ejercicio 3: Array con numeros pares del 2 al 50
arr3 = np.arange(2, 51, 2)
print(arr3)


In [ ]:
# Ejercicio 4: Array con numeros impares del 1 al 50 (supongo que quiso decir impares)
arr4 = np.arange(1, 51, 2)
print(arr4)


In [7]:
# Ejercio 5: Matriz 4x4 con valores aleatorios entre 0 y 1:
arr5 = np.random.rand(4, 4)
print(arr5)

[[0.18549414 0.91719355 0.2709208  0.27354789]
 [0.95441268 0.12711457 0.74726485 0.00523796]
 [0.85679061 0.6959562  0.5530257  0.9352358 ]
 [0.51262353 0.17761207 0.53686579 0.29345982]]


In [8]:
# Ejercicio 6: Suma elemento a elemento:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
# Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10
# -Ejemplo de algebra lineal .T intercambia filas por columnas
m1 = np.random.randint(1, 11, (3, 3))
m2 = np.random.randint(1, 11, (3, 3))
print(m1)
print(m2)
print(m1 @ m2.T)


[[ 5  4  2]
 [ 5  5  3]
 [ 3  1 10]]
[[ 1  2  9]
 [ 5  1  9]
 [10  7  7]]
[[ 31  47  92]
 [ 42  57 106]
 [ 95 106 107]]


In [10]:
# Ejercicio 7 con multiplicacion de matrices 3x3 de enteros aleatorios entre 1 y 10
m1 = np.random.randint(1, 11, (3, 3))
m2 = np.random.randint(1, 11, (3, 3))
mr1 = np.dot(m1, m2)
print(f"El producto de las matrices 3zx3 es:\n{mr1}")

El producto de las matrices 3zx3 es:
[[135  79 104]
 [ 92 100 101]
 [156 126 129]]


In [16]:
# Ejercicio 8: Array de 15 valores aleatorios (1-100) e imprime estadisticos:
arr8 = np.random.randint(1, 101, 15)
print(arr8)
print(f"Mximo : {np.max(arr8)} Minimo : {np.min(arr8)} Promedio : {np.mean(arr8)}")

[83 55 22 60 20 38 23 72 19 25 45 28 53 22 60]
Mximo : 83 Minimo : 19 Promedio : 41.666666666666664


In [18]:
# Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extraer su diagonal.
m5x5 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(m5x5)
print(m5x5)
print(f"La diagonal de la matriz 5x5 es:\n{diagonal}")


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
La diagonal de la matriz 5x5 es:
[ 1  7 13 19 25]


In [19]:
# Ejercicio 10: Matrix 5x5 (1-20), y calcular suma de cada fila y columna.
mf1 = np.random.randint(1, 21, (5, 5))
suma_filas = mf1.sum(axis=1)
suma_columnas = mf1.sum(axis=0)
print(f"Matriz aleatoria:\n{mf1}")
print(f"Suma de cada fila:\n{suma_filas}")
print(f"Suma de cada columna:\n{suma_columnas}")

Matriz aleatoria:
[[10 20 15 15  6]
 [ 7  6 17 12 10]
 [ 8 10 19 14  6]
 [ 4 16  2  5  7]
 [ 3 11 15 15  3]]
Suma de cada fila:
[66 52 57 34 47]
Suma de cada columna:
[32 63 68 61 32]
